core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('', views.HomePage.as_view(template_name="templates/landingpage.html")),
    path('post/', views.post, name="post"),
    path('feed/', views.userfeed, name="list_view"),
    path('search/', views.SearchResultsView.as_view(), name="search_results"),
    path('follow/<int:id_>', views.follow, name="follow"),
    path('registerservice/', views.register_service,name="register_service"),
    path('mypost/', views.mypost, name='mypost'),
    path('findnew/',views.findservices,name='findservices'),
]

digitalmarketing/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('userprofile.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

userprofile/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('profile/<int:id_>', views.profileDetailView, name="profile"),
    path('myaccount/', views.editprofile, name="editprofile"),
    path('', views.frontpage,name="frontpage")
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Service(models.Model):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE,
                                related_name="seller")
    Service_name = models.CharField(
        verbose_name="product/service name",
        null=False,
        max_length=50,
    )

    createDate = models.DateTimeField(
        verbose_name="date and time created",
        null=False,
        auto_created=True,
        default=timezone.now
    )

    description = models.TextField(
        verbose_name="service/product description",
        null=True,
        blank=True
    )

    avi = models.ImageField(null=True, blank=True, upload_to='avatar/')



    def __str__(self):
        return self.Service_name

    def desc_snippet(self):
        return self.description[:25]

class Post(models.Model):
    postby = models.ForeignKey(Service,
                               on_delete=models.CASCADE,
                               related_name="servicepost"
                               )
    postText = models.TextField(null=False, blank=False,verbose_name="post text")
    postImage = models.ImageField(upload_to="element/",blank=True, null=True)
    PostImageWebLink = models.CharField(max_length=1000,null=True,blank=True,verbose_name="input image from the web")
    postCreated = models.DateTimeField(auto_now=True)
    price = models.CharField(max_length=15, null=True, verbose_name="price of item",blank=True)

    def __str__(self):
        return self.postText[:25]

core/forms.py
from django import forms
from .models import Post,Service


class PostForm(forms.ModelForm):

    postText = forms.CharField(required=True, widget=forms.widgets.Textarea(attrs={'placeholder': 'Post', 'class': 'form-control'}))
    postImage = forms.ImageField(required=False, widget=forms.widgets.FileInput(attrs={'placeholder': 'Image', 'class': 'form-control'}))
    PostImageWebLink = forms.CharField(required=False, widget=forms.widgets.TextInput(attrs={'placeholder': 'input image from the web instead', 'class': 'form-control'}))
    price = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={'placeholder': 'price of item', 'class': 'form-control'}))

    class Meta:
        model = Post
        fields = ('postText', 'postImage')


class ServiceForm(forms.ModelForm):
    Service_name = forms.CharField(required=True,
                               widget=forms.widgets.TextInput(attrs={'id':'', 'placeholder': 'Service name', 'class': 'form-control mb-4'}))
    description = forms.CharField(required=True,
                               widget=forms.widgets.Textarea(attrs={'id':'', 'placeholder': 'Service description', 'class': 'form-control mb-4'}))
    avi = forms.ImageField(required=False, widget=forms.widgets.FileInput(
        attrs={'placeholder': 'Image', 'class': 'form-control'}))
    class Meta:
        model = Service
        fields = "__all__"
        exclude = ('user','createDate')

core/views.py
from django.shortcuts import get_list_or_404,redirect,get_object_or_404
from django.views.generic import ListView,TemplateView
from .models import *
from .forms import PostForm, ServiceForm
from django.shortcuts import render, HttpResponseRedirect
from django.db.models import Q
from userprofile.models import UserFollowing
from django.contrib.auth.decorators import login_required
from django.contrib import messages

class HomePage(TemplateView):
    template_name = "templates/landingpage.html"


class PostListView(ListView):
    model = Post
    template_name = "homepage.html"
    context_object_name = "posts"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


class SearchResultsView(ListView):
    model = Service
    template_name = 'serviceList.html'
    context_object_name = 'services'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('q')
        service_object_list = Service.objects.filter(
            Q(Service_name__contains=query) | Q(description__contains=query)
        )
        context['services'] = service_object_list
        post_object_list = Post.objects.filter(
            Q(postText__icontains=query)
        )
        context['posts'] = post_object_list
        return context


class AlternateSearchResultsView(ListView):
    model = Post
    template_name = 'serviceList.html'
    context_object_name = 'posts'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Post.objects.filter(
            Q(postText__icontains=query)
        )
        print(object_list)
        return object_list


@login_required(login_url="/")
def userfeed(request):
    """
    user feed
    :param request:
    :return:
    """

    usersIfollow = set()
    for user in request.user.follower.all():
        usersIfollow.add(user.following_user_id)
    follow_new_users = Service.objects.all()[:5]
    posts = Post.objects.all().filter(postby__in=usersIfollow)[0:25]

    return render(request, 'homepage.html', {'posts': posts, 'some_users': follow_new_users})

@login_required(login_url="/")
def post(request):
    """
    user posts adverts
    :param request:
    :return:
    """
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            try:
                service_instance = Service.objects.get(id=request.user.seller.id)
                post.postby = service_instance
                post.price = request.POST['price']
                if request.FILES:
                    docs = request.FILES
                    post.postImage = docs['postImage']
                post.save()
                return redirect('/')
            except Exception:
                messages.warning(request, 'please register your service first')
                return redirect('core:register_service')
    else:
        form = PostForm()
    return render(request, 'post.html', {'form': form})

@login_required(login_url="/")
def register_service(request):
    if request.method == "POST":
        form = ServiceForm(request.POST, request.FILES)
        if form.is_valid():
            service_form = form.save(commit=False)
            user_instance = User.objects.get(id=request.user.id)
            service_form.user = user_instance
            """docs = request.FILES
            service_form.avi = docs['avi']"""
            service_form.save()
            return redirect('/')
    else:
        form = ServiceForm()
    return render(request, 'registerService.html', {'form': form})


def follow(request, id_):
    if request.method == "GET":
        print("hello")
        userToFollow = get_object_or_404(Service, id=id_)
        try:
            UserFollowing.objects.create(
                user_id = request.user,
                following_user_id=userToFollow,
            )
        except Exception:
            print("dosent work")
            pass
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def mypost(request):
    try:
        service_instance = Service.objects.get(id=request.user.seller.id)
        post = service_instance.servicepost.all()
    except Exception:
        pass

    return render(request, 'myposts.html', {'posts': post})


def findservices(request):
    services = Service.objects.all().order_by('createDate')[:10]
    return render(request,'findservices.html',{'services':services})

core/templates/findservices.html
{% extends 'templates/base.html' %}
{% block body %}


{% for i in services %}
                <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
                  <div class="card-header">{{ i }}</div>
                    <div class="card-body">
                    <p class="card-text">{{ i.desc_snippet }}</p>
                    <form method="get" action="{% url 'core:follow' i.id %}">
                        <input type="submit" class="btn btn-primary" value="Follow" name="Follow">
                    </form>
                  </div>
                </div>
            {% endfor %}
{% endblock %}

core/templates/homepage.html
{% extends 'templates/base.html' %}
{% load ratings %}

{% block body %}
    <style>
    .avatar {
      vertical-align: middle;
      width: 50px;
      height: 50px;
      border-radius: 50%;
    }
    </style>
            {% for p in posts %}
                <div class="card">
                    <div class="card-header">
                        <a href="{% url 'accounts:profile' p.postby.id%}">{{ p.postby }}</a></p>
                    </div>
                    {% if p.postImage %}
                        <img class="card-img-top" src="{{p.postImage.url}}" alt="Card image cap">
                    {% elif p.PostImageWebLink %}
                        <img class="card-img-top" src="{{p.PostImageWebLink}}" alt="Card image cap">
                    {% endif %}
                    <div class="card-body">
                    <p class="card-text">desc : {{ p.postText }}</p>
                    <p class="card-text">price : {{ p.price }}</p>
                    </div>
                    <div class="card-footer">
                        {% ratings p %}
                    </div>
                </div>
                <br>
                <br>
            {% endfor %}

    {% if not posts %}
            <p class="text-info"> your feed is empty, follow some services....</p>
            {% for i in some_users %}
                <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
                  <div class="card-header">{{ i }}</div>
                    <div class="card-body">
                    <p class="card-text">{{ i.desc_snippet }}</p>
                    <form method="get" action="{% url 'core:follow' i.id %}">
                        <input type="submit" class="btn btn-primary" value="Follow" name="Follow">
                    </form>
                  </div>
                </div>
            {% endfor %}
    {% endif %}
{% endblock %}

core/templates/landingpage.html
{% extends 'templates/base.html' %}

{% block body %}
    <h1>landing page</h1>
{% endblock %}

core/templates/myposts.html
{% extends 'templates/base.html' %}
{% load ratings %}

{% block body %}
    <style>
    .avatar {
      vertical-align: middle;
      width: 50px;
      height: 50px;
      border-radius: 50%;
    }
    </style>
    <h3>my posts</h3>
    {% if posts %}
            {% for p in posts %}
                <div class="card">
                    <div class="card-header">
                        <a href="{% url 'accounts:profile' p.postby.id%}">{{ p.postby }}</a></p>
                    </div>
                    {% if p.image %}
                        <img class="card-img-top" src="{{p.image.url}}" alt="Card image cap">
                    {% elif p.PostImageWebLink %}
                        <img class="card-img-top" src="{{p.PostImageWebLink}}" alt="Card image cap">
                    {% endif %}
                    <div class="card-body">
                    <p class="card-text">desc : {{ p.postText }}</p>
                    <p class="card-text">price : {{ p.price }}</p>
                    </div>
                    <div class="card-footer">
                        {% ratings p %}
                    </div>
                </div>
                <br>
                <br>
            {% endfor %}
    {% else %}
        <div class="card border-success mb-3" style="max-width: 18rem;">
          <div class="card-header bg-transparent border-warning">Error</div>
          <div class="card-body text-success">
            <h5 class="card-title">you dont have any posts</h5>
            <p class="card-text">you should posts things....</p>
          </div>
          <div class="card-footer bg-transparent border-success">Footer</div>
        </div>
    {% endif %}
{% endblock %}

core/templates/post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<style>
    /*
    #E27D60
    #85cfdc
    */
    .card-header{
        background-color:  #E27D60;
        border-radius: 25px ;
        border-color:  #E27D60;
        border-width: 5px;
    }
    .card{
        border-radius: 25px ;
        border-color:  #E27D60;
        border-width: 5px;
        background: rgba(255, 255, 255, 0);
    }
    .btn{
        background-color:  #E27D60;
    }
    label{
        display: none;
    }
</style>
<div class="display-flex card text-center p-2">
    <div class="card-header m-2">
        <h2 class="text-white">New post</h2>
    </div>
    <div class="card-body">
        <form method="POST" class="post-form">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="save btn btn-default m-2 text-white">
                <svg class="bi bi-pencil-square" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                </svg>
                Save
            </button>
        </form>
    </div> 
</div>
{% endblock %}

core/templates/registerService.html
{% extends 'templates/base.html' %}
{% load crispy_forms_tags %}

{% block body %}

    <p class="h4 mb-4">register your buisness</p>
<form class="text-center border border-light p-5" method="post">
         {% csrf_token %}
        {{ form|crispy }}
    <button class="btn btn-info btn-block" type="submit">SAVE</button>

</form>
<!-- Default form contact -->
{% endblock %}

core/templates/serviceList.html
{% extends 'templates/base.html' %}
{% load ratings %}

{% block body %}
    <style>
    .avatar {
      vertical-align: middle;
      width: 50px;
      height: 50px;
      border-radius: 50%;
    }
    /*
    #E27D60
    #85cfdc
    */
    .card-header{
        background-color:  #E27D60;
        border-radius: 25px ;
        border-color:  #E27D60;
        border-width: 3px;
    }
    .card-body{
        background-color:  #E27D60;
    }
    .card{
        border-radius: 25px ;
        border-color:  #E27D60;
        border-width: 5px;
        background: rgba(255, 255, 255, 0);
    }
    </style>
        {% for s in services %}
        <div class="card mx-auto"  style="width: 50rem;">
            <div class="card-header m-2">
                <a href="{% url 'accounts:profile' s.user.id%}">{{ s.Service_name }}</a></p>
                {% if s.avi %}
                    <img class="card-img-top avatar img-circle" src="{{s.avi.url}}" alt="Card image cap">
                {% endif %}
            </div>
            <div class="card-body text-white">
                <p class="card-text">desc : {{ s.description }}</p>
                <p class="card-text">created : {{ s.createDate }}</p>
            </div>
        </div>
        {% endfor %}
{% endblock %}