core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('', views.HomePage.as_view(template_name="templates/landingpage.html")),
    path('post/', views.post, name="post"),
    path('feed/', views.userfeed, name="list_view"),
    path('search/', views.SearchResultsView.as_view(), name="search_results"),
    path('follow/<int:id_>', views.follow, name="follow"),
    path('registerservice/', views.register_service,name="register_service"),
    path('mypost/', views.mypost, name='mypost'),
    path('findnew/',views.findservices,name='findservices'),
]

digitalmarketing/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('userprofile.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

userprofile/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('profile/<int:id_>', views.profileDetailView, name="profile"),
    path('myaccount/', views.editprofile, name="editprofile"),
    path('', views.frontpage,name="frontpage")
]

templates/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
      <title>Merch-Agency</title>


  </head>

  <style>

    label{
        display: none;
    }
    nav{
      background-color: #2C3531;
      background: rgba(255, 255, 255, 0);
    }
    #bg-img{
      position:fixed;
    }
    </style>
  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-dark">
      <a class="navbar-brand text-white" href="#">Merch Agency</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse text-white" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        {% if request.user.is_authenticated %}
              <li class="nav-item active">
                <a class="nav-link text-white" href="{% url 'core:list_view' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'core:post' %}">Post</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'accounts:editprofile' %}">My account</a>
              </li>
            <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'core:mypost' %}">My Posts</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'core:findservices' %}">find new services</a>
            </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'accounts:logout' %}">logout</a>
              </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link disabled text-white" href="{% url 'accounts:frontpage' %}">register/login</a>
            </li>
        {% endif %}
        </ul>
          <span class="align-right">
            <form action="{% url 'core:search_results' %}" style="float: left" class="form-inline my-2 my-lg-0">
                <input name="q" class="form-control mr-sm-2" type="text" placeholder="Search..." aria-label="Search">
                <button class="btn btn btn-light my-2 my-sm-0" type="submit">Search</button>
            </form>
        </span>
      </div>
  </nav>

  <main role="main" class="container">
      <div class="row justify-content-center">
        <div class="col-8">

          <hr class="mt-0 mb-4">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
          {% block body %}

          {% endblock %}
        </div>
        </div>
  </main>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script>
    $("#post-form").submit(function(e){
        e.preventDefault();
        });</script>
  </body>
</html>

templates/landingpage.html
{% extends 'base.html' %}

{% block body %}
<style>
body {
  background-image: url("https://coolbackgrounds.io/images/unsplash/josh-bean-medium-9501ba9f.jpg");
  background-color: #cccccc;
}
.card {
    background-color: rgba(255,255,255, 0.2) !important;
}

</style>
  <!-- Icons Grid -->
    <div class="bg-image"></div>
    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center">
          <div class="col-md-5 p-lg-5 mx-auto my-5">
            <h1 class="display-4 font-weight-normal text-white">Merch Agency</h1>

              {% if request.user.is_authenticated %}
                  <p class="lead font-weight-normal text-white">welcome, {{ request.user }}</p>
              {% else %}
                  <p class="lead font-weight-normal text-white">building your brand with a hunger</p>
                  <p class="lead small font-weight-normal"></p>
                  <a class="btn btn-outline-secondary" href="{% url 'accounts:frontpage' %}">register or login</a>
              {% endif %}
          </div>
          <div class="product-device box-shadow d-none d-md-block"></div>
          <div class="product-device product-device-2 box-shadow d-none d-md-block"></div>
    </div>
        <center>
        <div class="card-deck">
            <div class="card" style="width: 15rem;">
          <img class="card-img-top" src="https://www.berley.co.uk/wp-content/uploads/2018/01/hero.jpg" alt="Card image cap">
          <div class="card-body">
            <p class="card-text text-white">We don’t just believe in small business we live it!!</p>
          </div>
        </div>

          <div class="card" style="width: 15rem;">
          <img class="card-img-top" src="https://cdn.dribbble.com/users/639339/screenshots/2579265/rise-and-grind.jpg" alt="Card image cap">
          <div class="card-body">
            <p class="card-text text-white">we are a platform which assits small businesses to advertise their products</p>
          </div>
        </div>

            <div class="card" style="width: 15rem;">
          <img class="card-img-top" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/content/wi/art/brand-building-8ea6c101c6.png" alt="Card image cap">
          <div class="card-body">
            <p class="card-text text-white">Focus on building the best possible business. If you are great, people will notice and opportunities will appear</p>
          </div>
        </div>
        </div>
    </center>


{% endblock %}